# Site settings
author: Nick Spangler
title: An Actor Who Codes
header-img: img/home-bg.png
email: spangleyman@mac.com
copyright_name: Nick Spangler
description: > # this means to ignore newlines until "baseurl:"
  From Silicon Valley, to Broadway, and back again...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  NickSpangler

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
